name: Build and run test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install -y meson ninja-build lcov gcovr libglib2.0-dev libgranite-dev libgtk-3-dev libcairo2-dev meson valac libsoup2.4-dev libsoup-gnome2.4-dev libxmlbird-dev gettext

    - uses: actions/checkout@v3

    - name: Configure meson
      run: meson setup build

    - name: Build
      run: ninja -C build

    - name: Test
      run: ninja -C build test

    - name: Coverage
      run: ./coverage.sh

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
